require 'yaml'
require_relative './fruitshop/cash_register'
require_relative './fruitshop/pricer'
require_relative './fruitshop/discounter'
require_relative './fruitshop/product'
require_relative './fruitshop/session'
